"""P1 (F&G part): integrity checks on the pinned Fear & Greed data.

Usage: python scripts/01_fear_greed_integrity.py --mirror /path/to/fear-greed-data-clone

Integrity-only: uses F&G values for all dates (including the holdout window) but never touches prices,
returns or signals, so the holdout lock (protocol §4) is not breached.
Writes reports/phase1_fear_greed.md, data/raw/fear_greed/MANIFEST.json, data/processed/fear_greed.parquet.
"""
import argparse
import hashlib
import json
import statistics as st
import subprocess
from datetime import date
from pathlib import Path

import exchange_calendars as xcals
import numpy as np
import pandas as pd

from fgbt.data.fear_greed import (
    CNN_JSON_PATH, ERA_SPLIT, MIRROR_SHA, MIRROR_URL, OLD_ERA_PATH,
    git_show, implied_component_count, load_pinned, parse_cnn_json, parse_old_csv,
)
from fgbt.data.validate import extra_non_trading_days, gap_runs, missing_trading_days

ROOT = Path(__file__).resolve().parents[1]
BANDS = [0, 25, 45, 55, 75, 100.0001]

# Exceptions the user accepted at Gate P1 on 2026-10-02. The verdict is computed: any detected exception
# not in this set makes the gate PENDING until the user accepts it (and it is added here in a reviewed commit).
ACCEPTED_EXCEPTIONS = {
    "revisions": "Settled (revised) CNN history is used; first-print risk handled by amendment A1's perturbation test.",
    "gap OLD 2020-06-08..2020-07-08": "OLD-era gap of 22 sessions: no signal can fire inside it.",
    "incomplete components": "2021 days averaging 5–6 of 7 components are flagged (`fg_incomplete`); P2 reports with and without.",
    "gap NEW 2026-03-12..2026-03-12": "2026-03-12 missing (holdout window).",
}


def band(x):
    return int(np.digitize([x], BANDS)[0])


def compare(a: pd.Series, b: pd.Series):
    common = a.index.intersection(b.index)
    x, y = a[common], b[common]
    diff = y - x
    return {
        "n": len(common), "first": min(common) if len(common) else None, "last": max(common) if len(common) else None,
        "corr": float(np.corrcoef(x, y)[0, 1]) if len(common) > 2 else float("nan"),
        "mean_diff": float(diff.mean()) if len(common) else float("nan"),
        "med_abs": float(diff.abs().median()) if len(common) else float("nan"),
        "max_abs": float(diff.abs().max()) if len(common) else float("nan"),
        "n_changed": int((diff.abs() > 1e-9).sum()),
        "same_band": float(np.mean([band(p) == band(q) for p, q in zip(x, y)])) if len(common) else float("nan"),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mirror", required=True)
    args = ap.parse_args()
    repo = args.mirror
    head = subprocess.run(["git", "-C", repo, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()

    out = []
    w = out.append
    w("# Phase 1: Fear & Greed data integrity\n")
    w(f"Generated by `scripts/01_fear_greed_integrity.py` from mirror `{MIRROR_URL}` at pinned commit `{MIRROR_SHA}` "
      f"(clone HEAD `{head}`). Integrity-only: no prices, returns or signals are used.\n")

    # --- manifest
    manifest = {"source": MIRROR_URL, "commit": MIRROR_SHA, "files": {}}
    for p in (OLD_ERA_PATH, CNN_JSON_PATH):
        manifest["files"][p] = hashlib.sha256(git_show(repo, MIRROR_SHA, p).encode()).hexdigest()
    (ROOT / "data/raw/fear_greed/MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")

    df = load_pinned(repo)
    (ROOT / "data/processed").mkdir(parents=True, exist_ok=True)
    df.to_parquet(ROOT / "data/processed/fear_greed.parquet")

    # --- 1. coverage
    w("## 1. Coverage, range, calendar\n")
    w("| Era | First | Last | Rows | Min | Max | Missing NYSE sessions | Non-session rows |")
    w("|---|---|---|---|---|---|---|---|")
    gap_lines, detected = [], []
    for era in ("OLD", "NEW"):
        e = df[df.era == era]
        miss = missing_trading_days(e.index)
        extra = extra_non_trading_days(e.index)
        w(f"| {era} | {e.index.min()} | {e.index.max()} | {len(e)} | {e.fg.min():.2f} | {e.fg.max():.2f} | {len(miss)} | {len(extra)} |")
        for a, b, n in gap_runs(miss):
            detected.append(f"gap {era} {a}..{b}")
            gap_lines.append(f"- {era}: {a} → {b} ({n} session{'s' if n > 1 else ''})")
        for d in extra:
            gap_lines.append(f"- {era}: row on non-NYSE-session date {d}")
            detected.append(f"non-session row {era} {d}")
    w("\nMissing-session runs and anomalies:\n")
    w("\n".join(gap_lines) if gap_lines else "- none")
    w("\nRule (protocol §2): values are never forward-filled for more than 3 sessions. Inside a longer gap no new signal can fire.\n")

    # --- 2. revisions
    w("## 2. Does CNN revise past values? (point-in-time check)\n")
    pinned_new, _ = parse_cnn_json(git_show(repo, MIRROR_SHA, CNN_JSON_PATH))
    commits = subprocess.run(["git", "-C", repo, "log", "--format=%H %ad", "--date=short", "--", CNN_JSON_PATH],
                             capture_output=True, text=True, check=True).stdout.split("\n")
    sessions = xcals.get_calendar("XNYS", start="2020-01-01").sessions.date
    n_sessions = lambda a, b: int(np.searchsorted(sessions, b) - np.searchsorted(sessions, a))  # noqa: E731
    pin_end = pinned_new.index.max()
    rev, prev_close_rows, n_snap, ghost = [], [], 0, {}
    for line in filter(None, commits):
        sha, d = line.split()
        try:
            hist, cur = parse_cnn_json(git_show(repo, sha, CNN_JSON_PATH))
        except (ValueError, KeyError, json.JSONDecodeError):
            continue
        n_snap += 1
        end = hist.index.max()
        for x in hist.index.difference(pinned_new.index):
            ghost[x] = ghost.get(x, 0) + 1
        for dd, v in hist.items():
            # only dates whose pinned value has had >= 60 sessions to settle
            if dd in pinned_new.index and n_sessions(dd, pin_end) >= 60:
                rev.append((n_sessions(dd, end), v - pinned_new[dd]))
        # previous_close vs final stored value of the session before the snapshot's current date
        cur_day = pd.Timestamp(cur["timestamp"]).date()
        prior = pinned_new[pinned_new.index < cur_day]
        if len(prior) and cur.get("previous_close") is not None:
            prev_close_rows.append((cur_day, prior.index[-1], float(cur["previous_close"]), float(prior.iloc[-1])))
    rv = pd.DataFrame(rev, columns=["age", "diff"])
    rv["abs"] = rv["diff"].abs()
    rv["bucket"] = pd.cut(rv.age, [-1, 0, 1, 5, 10, 20, 30, 40, 60, 10**6],
                          labels=["0", "1", "2–5", "6–10", "11–20", "21–30", "31–40", "41–60", ">60"])
    w(f"{n_snap} saved snapshots of the CNN API (2023-12-31, then 2026-04-19 → 2026-10-02) are compared with the pinned "
      f"snapshot. Only dates that have had ≥ 60 sessions to settle in the pinned snapshot are used. "
      f"*Age* = sessions between the date and the last date in that snapshot (0 = first print).\n")
    w("| Age (sessions) | Pairs | Share revised | Mean abs revision | P90 abs | Max abs |")
    w("|---|---|---|---|---|---|")
    for b, g in rv.groupby("bucket", observed=True):
        w(f"| {b} | {len(g)} | {100 * (g['abs'] > 1e-9).mean():.1f}% | {g['abs'].mean():.2f} | {g['abs'].quantile(.9):.2f} | {g['abs'].max():.2f} |")
    settled = rv[rv.age > 40]
    if (rv["abs"] > 1e-9).any():
        detected.append("revisions")
    if (settled["abs"] > 1e-9).any():
        detected.append("revisions after 40 sessions")
    w(f"\n**Result: CNN revises published values for about 40 sessions, then they are final** "
      f"({int((settled['abs'] > 1e-9).sum())} revisions among {len(settled)} pairs older than 40 sessions). "
      f"A live trader acts on the first print, while history holds the settled value. The first print's error is typically "
      f"≈1–3 points (max {rv[rv.age <= 1]['abs'].max():.1f}). This is a hidden look-ahead channel, handled by protocol amendment A1 (§11).\n")
    if ghost:
        nyse = set(sessions)
        w("Dates that appeared in some snapshots and were later removed: "
          + ", ".join(f"{k} ({v}×, {'NYSE session, now missing' if k in nyse else 'NYSE holiday'})"
                      for k, v in sorted(ghost.items()))
          + ". Holiday rows are dropped. A removed real session is a missing value (never filled for more than 3 sessions).\n")
    # first-print error distribution (age 0-1) is saved for the perturbation test of amendment A1
    rv[rv.age <= 1][["age", "diff"]].to_csv(ROOT / "data/processed/fg_first_print_errors.csv", index=False)

    pc = pd.DataFrame(prev_close_rows, columns=["snapshot_day", "session", "previous_close", "stored"]).drop_duplicates("session")
    pc["diff"] = pc.previous_close - pc.stored
    w("### `previous_close` vs stored end-of-day value\n")
    w(f"Sessions compared: {len(pc)}. Mean diff {pc['diff'].mean():+.3f}, median |diff| {pc['diff'].abs().median():.3f}, "
      f"max |diff| {pc['diff'].abs().max():.3f}, share with |diff| > 0.01: {100 * (pc['diff'].abs() > 0.01).mean():.1f}%.\n")
    w("Interpretation: the live page's 'previous close' can differ from the stored daily value, because components keep updating after "
      "the cash close. The backtest uses stored end-of-day values with availability at 00:00 UTC on d+1. The live routine (P8) must read "
      "the value after that time so it matches what was tested.\n")

    # --- 3. era break
    w("## 3. OLD vs NEW index: structural break\n")
    snap0 = "2cb495c"  # first mirror commit (2023-12-31): holds the independent comparison datasets
    others = {
        "openstockalert (old index)": parse_old_csv(git_show(repo, snap0, "datasets/openstockalert_fear_greed_data.csv")),
        "alexey-formalmethods (old index)": parse_old_csv(git_show(repo, snap0, "datasets/alexey-formalmethods_fear_greed_data.csv")),
    }
    archive = parse_old_csv(git_show(repo, snap0, "datasets/archive_org_fear_greed_data.csv"))
    old_series = df[df.era == "OLD"].fg
    new_series = df[df.era == "NEW"].fg
    w("| Comparison | Overlap | n | Corr | Mean diff (2nd − 1st) | Median abs diff | Same CNN band |")
    w("|---|---|---|---|---|---|---|")
    pairs = [("archive.org live snapshots → OLD series used", archive, old_series),
             ("archive.org live snapshots → NEW (CNN API)", archive, new_series)]
    pairs += [(f"{k} → NEW (CNN API)", v, new_series) for k, v in others.items()]
    for name, a, b in pairs:
        c = compare(a, b)
        w(f"| {name} | {c['first']} → {c['last']} | {c['n']} | {c['corr']:.3f} | {c['mean_diff']:+.2f} | {c['med_abs']:.2f} | {100 * c['same_band']:.1f}% |")
    w("\nThe archive.org snapshots are weekly (Fridays) captures of what money.cnn.com showed at that moment, the only point-in-time "
      "reference available. The OLD series tracks them closely. The CNN API history for 2021–22 does not, so the API history "
      "before its live launch is a recomputation under the current methodology. **Consequence (protocol §2):** the eras are "
      "analysed separately, and any threshold is also tested as a within-era percentile.\n")

    # --- 4. components
    w("## 4. NEW era: incomplete component averages\n")
    k = pd.Series({d: implied_component_count(v) for d, v in new_series.items()})
    tab = k.groupby([pd.Index([d.year for d in k.index]), k.values]).size().unstack(fill_value=0)
    w("Implied number of components averaged (7 = complete), by year:\n")
    w("| Year | " + " | ".join(f"k={c}" for c in tab.columns) + " |")
    w("|---|" + "---|" * len(tab.columns))
    for y, r in tab.iterrows():
        w(f"| {y} | " + " | ".join(str(int(v)) for v in r.values) + " |")
    w("\nDays with k < 7 are flagged (`fg_incomplete`) in the processed data. P2 reports results with and without them.\n")

    # --- 5. distribution by research segment (DEV/VAL only; holdout distribution intentionally not reported)
    w("## 5. Distribution by research segment (holdout excluded)\n")
    w("| Segment | n | Mean | SD | P5 | P50 | P95 | Days < 25 | Days ≥ 75 |")
    w("|---|---|---|---|---|---|---|---|---|")
    for name, a, b in (("DEV", date(2011, 1, 3), date(2020, 12, 31)), ("VAL", date(2021, 2, 1), date(2024, 12, 31))):
        s = df[(df.index >= a) & (df.index <= b)].fg
        q = s.quantile([0.05, 0.5, 0.95])
        w(f"| {name} | {len(s)} | {s.mean():.1f} | {s.std():.1f} | {q.iloc[0]:.1f} | {q.iloc[1]:.1f} | {q.iloc[2]:.1f} | "
          f"{(s < 25).sum()} | {(s >= 75).sum()} |")

    if any(v is not None and v < 7 for v in k.values):
        detected.append("incomplete components")
    w("\n## Gate P1 (F&G part): verdict (computed)\n")
    unaccepted = [x for x in detected if x not in ACCEPTED_EXCEPTIONS]
    if unaccepted:
        w("**PENDING: exceptions not yet accepted by the user:** " + "; ".join(unaccepted) + "\n")
    else:
        w("**PASSED: every detected exception was accepted by the user (2026-10-02):**\n")
    for x in detected:
        if x in ACCEPTED_EXCEPTIONS:
            w(f"- `{x}`: {ACCEPTED_EXCEPTIONS[x]}")
    w("")
    w("The price-data part of P1 is pending the TradingView exports (DATA.md).\n")

    df["fg_incomplete"] = [bool(d in k.index and k[d] is not None and k[d] < 7) for d in df.index]
    df.to_parquet(ROOT / "data/processed/fear_greed.parquet")
    (ROOT / "reports/phase1_fear_greed.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
