"""P1 (prices): integrity checks on TradingView exports in data/raw/tradingview/.

Usage: python scripts/02_price_integrity.py
Integrity-only: no signals or strategy returns. OHLC/calendar/roll checks cover all dates (no return information);
the return-outlier screen covers only dates before the locked holdout (protocol §4). Writes reports/phase1_prices.md and
data/raw/tradingview/MANIFEST.json. The verdict is computed: every detected exception must be in ACCEPTED_EXCEPTIONS.
"""
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from fgbt.data.prices import parse_filename, parse_tradingview_csv
from fgbt.data.validate import (
    detect_rolls, extra_sessions, gap_runs, missing_sessions, nan_bars, ohlc_violations, off_tick_grid,
    return_outliers,
)
from fgbt.instruments import INSTRUMENTS
from fgbt.splits import research_view

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data/raw/tradingview"

# Filled in only after the user reviews a report and accepts a specific exception.
ACCEPTED_EXCEPTIONS: dict[str, str] = {}


def main():
    files = sorted(p for p in RAW.glob("*.csv"))
    out, detected, manifest, loaded = [], [], {}, {}
    w = out.append
    w("# Phase 1: Price data integrity (TradingView exports)\n")
    w("Generated by `scripts/02_price_integrity.py`. Integrity-only: no signals or strategy returns are computed.\n")
    if not files:
        w("**No export files in `data/raw/tradingview/` yet.** See DATA.md §2 (start with the pilot `ES1_ETH_1D_badj.csv`).\n")
        detected.append("no files")
    for p in files:
        blob = p.read_bytes()  # hash the exact bytes on disk (CRLF preserved)
        manifest[p.name] = {"sha256": hashlib.sha256(blob).hexdigest(), "bytes": len(blob),
                            "source": "TradingView chart export by the user (DATA.md §2)",
                            "first_validated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%d")}
        try:
            meta = parse_filename(p.name)
            df = parse_tradingview_csv(blob.decode("utf-8-sig"), meta["timeframe"])
        except (ValueError, UnicodeDecodeError) as e:
            w(f"## `{p.name}`\n\n**Unreadable:** {e}\n")
            detected.append(f"unreadable {p.name}")
            continue
        manifest[p.name].update(meta)
        loaded[p.name] = (meta, df)
        w(f"## `{p.name}`\n")
        w(f"- Settings from name: {meta}")
        w(f"- Bars: {len(df)}, first {df.index[0]}, last {df.index[-1]}, columns {list(df.columns)}")
        nan = nan_bars(df)
        w(f"- Bars with missing OHLC values: {len(nan)} {nan[:5]}")
        if nan:
            detected.append(f"nan {p.name}")
        bad = ohlc_violations(df)
        w(f"- OHLC violations (low > open/close, high < open/close, non-positive): {len(bad)} {bad[:5]}")
        if bad:
            detected.append(f"ohlc {p.name}")
        if not meta["adjusted"]:
            grid = off_tick_grid(df, INSTRUMENTS[meta["symbol"]].tick_size)
            w(f"- Prices off the {INSTRUMENTS[meta['symbol']].tick_size} tick grid: {len(grid)} {grid[:5]}")
            if grid:
                detected.append(f"off-grid {p.name}")
        if meta["timeframe"] == "1D":
            miss = missing_sessions(df.index)
            extra = extra_sessions(df.index)
            runs = gap_runs(sorted(miss["regular"] + miss["nyse_holiday"]), calendar="CMES")
            runs = [r for r in runs if any(r[0] <= d <= r[1] for d in miss["regular"])]
            w(f"- Missing regular CME sessions: {len(miss['regular'])}; contiguous gaps containing them "
              f"(CME sessions, holidays included): {[(str(a), str(b), n) for a, b, n in runs[:8]]}")
            w(f"- Missing Globex sessions on NYSE holidays (informational): {len(miss['nyse_holiday'])}")
            w(f"- Bars on non-CME-session dates: {len(extra)} {extra[:5]}")
            if miss["regular"]:
                detected.append(f"missing sessions {p.name}")
            if extra:
                detected.append(f"extra sessions {p.name}")
            outl = return_outliers(research_view(df))
            w(f"- Close-to-close returns beyond 8 robust sigmas, pre-holdout only (review, never dropped): "
              f"{len(outl)} {outl[:8]}")
            if outl:
                detected.append(f"outliers {p.name}")
        else:
            w(f"- Session/outlier/roll checks apply to 1D files only; {meta['timeframe']} is checked for OHLC sanity here "
              f"and is reconciled against the 1D file in P2 resampling checks.")
        w("")

    for name, (meta, df) in loaded.items():
        if meta["timeframe"] == "1D" and meta["adjusted"]:
            raw_name = name.replace("_badj", "_raw")
            if raw_name in loaded:
                r = detect_rolls(df["close"], loaded[raw_name][1]["close"])
                w(f"## Roll detection: `{name}` vs `{raw_name}`\n")
                w(f"Rolls detected: {len(r)}; outside the 12 days before a quarterly expiry: {int((~r.in_expected_window).sum())}\n")
                w("| Session | Gap (points) | Expiry | In window |")
                w("|---|---|---|---|")
                for _, x in r.iterrows():
                    w(f"| {x.session} | {x.gap_points:+.2f} | {x.expiry} | {x.in_expected_window} |")
                w("")
                if (~r.in_expected_window).any():
                    detected.append(f"rolls outside window {name}")

    w("## Gate P1 (prices): verdict (computed)\n")
    unaccepted = [x for x in detected if x not in ACCEPTED_EXCEPTIONS]
    w(("**PENDING:** " + "; ".join(unaccepted)) if unaccepted else "**PASSED** (all detected exceptions accepted).")
    RAW.mkdir(parents=True, exist_ok=True)
    (RAW / "MANIFEST.json").write_text(json.dumps(manifest, indent=2, default=str) + "\n")
    (ROOT / "reports/phase1_prices.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
