"""P2 preliminaries from F&G alone (no prices, no returns): persistence and event counts per research segment.

Usage: python scripts/03_fg_facts.py   (requires data/processed/fear_greed.parquet from script 01)
The holdout is excluded via fgbt.splits.research_view. These facts set statistical power before any result exists.
"""
import math
from pathlib import Path

import pandas as pd

from fgbt.research.events import cross_back_events, independent_events
from fgbt.splits import DEV, VAL, research_view
from fgbt.validation.bootstrap import ar1_fit
from fgbt.data.validate import gap_runs, missing_trading_days

ROOT = Path(__file__).resolve().parents[1]
THRESHOLDS = (10, 15, 20, 25)


def contiguous_pieces(s: pd.Series, max_gap: int = 3) -> list[pd.Series]:
    """Split at missing-session runs longer than max_gap so AR(1) never bridges a data hole."""
    cuts = [b for a, b, n in gap_runs(missing_trading_days(s.index)) if n > max_gap]
    pieces, start = [], s.index[0]
    for b in cuts:
        pieces.append(s[(s.index >= start) & (s.index <= b)])
        start = b
    pieces.append(s[s.index > start] if cuts else s)
    return [p for p in pieces if len(p) > 50]


def main():
    fg_all = research_view(pd.read_parquet(ROOT / "data/processed/fear_greed.parquet"))
    variants = {"all days": fg_all, "excl. incomplete-component days": fg_all[~fg_all["fg_incomplete"]]}
    segs = {"DEV": DEV, "VAL": VAL}
    out = ["# Phase 2 preliminaries: F&G persistence and event counts (no returns used)\n",
           "Generated by `scripts/03_fg_facts.py`. Holdout excluded. Events follow protocol §5: an independent episode needs "
           "at least 20 observed sessions with the condition false. Events are detected on the full DEV+VAL series and "
           "then assigned to the segment of their date, so episodes running across a boundary are never double counted. "
           "Each table is reported with and without the 2021 days averaging fewer than 7 components (Phase 1 exception 3).\n",
           "## Persistence (AR(1), never bridging data gaps longer than 3 sessions)\n",
           "| Variant | Segment | n | phi | Half-life (sessions) | Shock sd |", "|---|---|---|---|---|---|"]
    for vname, fg in variants.items():
        for name, (a, b) in segs.items():
            s = fg[(fg.index >= a) & (fg.index <= b)].fg
            phi, _, sd, _ = ar1_fit([p.to_numpy() for p in contiguous_pieces(s)])
            out.append(f"| {vname} | {name} | {len(s)} | {phi:.4f} | {math.log(0.5) / math.log(phi):.1f} | {sd:.2f} |")
    out += ["\nphi close to 1 means a highly persistent predictor. That is why predictive tests use the null-preserving bootstrap "
            "(protocol R6) and never plain OLS t-statistics.\n",
            "## Independent events per threshold (sets statistical power)\n",
            "| Variant | Segment | T | H2 events (F&G < T) | H3 events (cross back ≥ T) |", "|---|---|---|---|---|"]
    for vname, fg in variants.items():
        s = fg.fg
        for t in THRESHOLDS:
            h2 = independent_events(s, lambda x, t=t: x < t, sep=20)
            h3 = cross_back_events(s, t, sep=20)
            for name, (a, b) in segs.items():
                n2 = sum(a <= d <= b for d in h2)
                n3 = sum(a <= d <= b for d in h3)
                out.append(f"| {vname} | {name} | {t} | {n2} | {n3} |")
    out.append("\nRule of thumb for event tests: with n independent events and a per-event return sd of σ, the smallest mean "
               "effect detectable at 5% (two-sided, 80% power) is ≈ 2.8·σ/√n. With n = 20 that is ≈ 0.63σ. Any configuration "
               "with < 30 events is capped at PROVISIONAL (protocol §8).")
    (ROOT / "reports/phase2_fg_facts.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
